package spec

// FabricatorWorkbench returns the built-in specification for the spreadsheet
// contract historically implemented by Fabricator. It accepts either the
// human-label header used by Google Sheets or the two-row machine/human export
// found in Fabricator fixtures.
func FabricatorWorkbench() *Transformation {
	createUpdate := []Operation{OperationCreate, OperationUpdate}
	createOnly := []Operation{OperationCreate}
	media := []Operation{OperationCreate, OperationAddMedia}

	fields := []Field{
		{Name: "id", Label: "Upload ID", Hub: "Extra.id", Codec: "unsigned", Cardinality: 1, Operations: createOnly},
		{Name: "parent_id", Label: "Page/Item Parent ID", Hub: "Extra.parent_id", Codec: "unsigned", Cardinality: 1, Operations: createOnly},
		{Name: "field_weight", Label: "Child Sort Order", Hub: "Extra.field_weight", Codec: "integer", Cardinality: 1, Operations: createUpdate},
		{Name: "node_id", Label: "Node ID", Aliases: []string{"nid"}, Hub: "Extra.node_id", Codec: "unsigned", Cardinality: 1, Operations: []Operation{OperationUpdate, OperationAddMedia}},
		{Name: "field_member_of", Label: "Parent Collection", Hub: "Relations.member_of", Codec: "multi", Operations: createUpdate},
		{Name: "field_model", Label: "Object Model", Hub: "ObjectModel", Cardinality: 1, RequiredFor: createOnly, Operations: createUpdate},
		{Name: "file", Label: "File Path", Hub: "Files.primary", Codec: "file", Cardinality: 1, Operations: media},
		{Name: "field_add_coverpage", Label: "Add Coverpage (Y/N)", Hub: "AddCoverpage", Codec: "boolean", Cardinality: 1, Operations: createUpdate},
		{Name: "title", Label: "Title", Hub: "Title", Cardinality: 1, RequiredFor: createOnly, Operations: createUpdate},
		{Name: "field_full_title", Label: "Full Title", Hub: "FullTitle", Cardinality: 1, RequiredFor: createOnly, Operations: createUpdate},
		{Name: "published", Label: "Make Public (Y/N)", Hub: "IsPublic", Codec: "boolean", Cardinality: 1, Operations: createUpdate},
		{Name: "field_linked_agent.name", Label: "Creator/Contributor Name 1", Aliases: []string{"Contributor Name 1", "Contributor"}, Hub: "Contributors.Name", Codec: "contributors", Operations: createUpdate},
		{Name: "field_linked_agent.rel_type", Label: "Contributor Relator 1", Hub: "Contributors.RoleCode", Codec: "contributors", Operations: createUpdate},
		{Name: "field_linked_agent.vid", Label: "Contributor Type 1", Hub: "Contributors.Type", Codec: "contributors", Operations: createUpdate},
		{Name: "field_linked_agent.entity.field_identifier.attr0=orcid", Label: "ORCID Number 1", Hub: "Contributors.ORCID", Codec: "contributors", Operations: createUpdate},
		{Name: "field_linked_agent.entity.field_contributor_status", Label: "Contributor Status 1", Hub: "Contributors.Status", Codec: "contributors", Operations: createUpdate},
		{Name: "field_linked_agent.entity.field_email", Label: "Contributor Email 1", Hub: "Contributors.Email", Codec: "contributors", Operations: createUpdate},
		{Name: "field_linked_agent.entity.field_relationships", Label: "Contributor Institution 1", Hub: "Contributors.Affiliation", Codec: "contributors", Operations: createUpdate},
		{Name: "field_department_name", Label: "Related Department", Hub: "Departments", Codec: "multi", Operations: createUpdate},
		{Name: "field_resource_type", Label: "Resource Type", Hub: "ResourceType", Cardinality: 1, OptionalForObjectModels: []string{"Page", "Sub-Collection"}, Operations: createUpdate},
		{Name: "field_genre", Label: "Genre (Getty AAT)", Aliases: []string{"Genre __(Getty AAT)__"}, Hub: "Genre", Codec: "multi", Operations: createUpdate},
		{Name: "field_edtf_date_issued", Label: "Creation Date", Hub: "Dates.issued", Codec: "edtf", Operations: createUpdate},
		{Name: "field_date_season", Label: "Season", Hub: "Extra.date_season", Cardinality: 1, Operations: createUpdate},
		{Name: "field_edtf_date_captured", Label: "Date Captured", Hub: "Dates.captured", Codec: "edtf", Operations: createUpdate},
		{Name: "field_edtf_date_embargo", Label: "Embargo Until Date", Hub: "Dates.available", Codec: "edtf", Operations: createUpdate},
		{Name: "field_publisher", Label: "Publisher", Hub: "Publisher", Cardinality: 1, Operations: createUpdate},
		{Name: "field_edition", Label: "Edition", Hub: "Edition", Cardinality: 1, Operations: createUpdate},
		{Name: "field_language", Label: "Language", Hub: "Language", Cardinality: 1, Operations: createUpdate},
		{Name: "field_physical_form", Label: "Physical Format (Getty AAT)", Aliases: []string{"Physical Format __(Getty AAT)__"}, Hub: "PhysicalForm", Codec: "multi", Operations: createUpdate},
		{Name: "field_media_type", Label: "File Format (MIME Type)", Aliases: []string{"File Format __(MIME Type)__"}, Hub: "Files.mime_type", Cardinality: 1, Operations: createUpdate},
		{Name: "field_extent.attr0=page", Label: "Page Count", Hub: "PageCount", Codec: "integer", Cardinality: 1, Operations: createUpdate},
		{Name: "field_extent.attr0=dimensions", Label: "Dimensions", Hub: "Dimensions", Cardinality: 1, Operations: createUpdate},
		{Name: "field_extent.attr0=bytes", Label: "File Size", Hub: "Files.size_bytes", Codec: "integer", Cardinality: 1, Operations: createUpdate},
		{Name: "field_extent.attr0=minutes", Label: "Run Time (HH:MM:SS)", Hub: "Duration", Cardinality: 1, Operations: createUpdate},
		{Name: "field_digital_origin", Label: "Digital Origin", Hub: "DigitalOrigin", Cardinality: 1, Operations: createUpdate},
		{Name: "field_abstract.attr0=description", Label: "Description", Hub: "Description", Cardinality: 1, Operations: createUpdate},
		{Name: "field_abstract.attr0=abstract", Label: "Abstract", Hub: "Abstract", Cardinality: 1, Operations: createUpdate},
		{Name: "field_note.attr0=preferred-citation", Label: "Preferred-Citation (included only in Fritz Lab and Environmental reports)", Hub: "PreferredCitation", Cardinality: 1, Operations: createUpdate},
		{Name: "field_note.attr0=capture-device", Label: "Capture Device", Hub: "CaptureDevice", Cardinality: 1, Operations: createUpdate},
		{Name: "field_note.attr0=ppi", Label: "PPI", Hub: "PPI", Codec: "integer", Cardinality: 1, Operations: createUpdate},
		{Name: "field_note.attr0=collection", Label: "Archival Collection", Hub: "ArchivalLocation.Collection", Cardinality: 1, Operations: createUpdate},
		{Name: "field_note.attr0=box", Label: "Archival Box", Hub: "ArchivalLocation.Box", Cardinality: 1, Operations: createUpdate},
		{Name: "field_note.attr0=series", Label: "Archival Series", Hub: "ArchivalLocation.Series", Cardinality: 1, Operations: createUpdate},
		{Name: "field_note.attr0=folder", Label: "Archival Folder", Hub: "ArchivalLocation.Folder", Cardinality: 1, Operations: createUpdate},
		{Name: "field_local_restriction", Label: "Local Restriction", Hub: "LocalRestriction", Codec: "restriction", Cardinality: 1, Operations: createUpdate},
		{Name: "field_subject_lcsh", Label: "Subject Topic (LCSH)", Aliases: []string{"Subject Topic __(LCSH)__"}, Hub: "Subjects.lcsh", Codec: "multi", Operations: createUpdate},
		{Name: "field_keywords", Label: "Keyword", Hub: "Subjects.keywords", Codec: "multi", Operations: createUpdate},
		{Name: "field_subjects_name", Label: "Subject Name (LCNAF)", Aliases: []string{"Subject Name __(LCNAF)__"}, Hub: "Subjects.lcnaf", Codec: "multi", Operations: createUpdate},
		{Name: "field_geographic_subject.vid=geographic_naf", Label: "Subject Geographic (LCNAF)", Aliases: []string{"Subject Geographic __(LCNAF)__"}, Hub: "Subjects.geographic_naf", Codec: "multi", Operations: createUpdate},
		{Name: "field_geographic_subject.vid=geographic_local", Label: "Subject Geographic (Local)", Aliases: []string{"Subject Geographic __(Local)__"}, Hub: "Subjects.geographic_local", Codec: "multi", Operations: createUpdate},
		{Name: "field_subject_hierarchical_geo", Label: "Hierarchical Geographic (Getty TGN)", Aliases: []string{"Hierarchical Geographic __(Getty TGN)__"}, Hub: "Subjects.getty_tgn", Codec: "multi", Operations: createUpdate},
		{Name: "field_related_item.title", Label: "Source Publication Title", Hub: "Publication.Title", Cardinality: 1, Operations: createUpdate},
		{Name: "field_related_item.identifier_type=issn", Label: "Source Publication L-ISSN", Hub: "Publication.LIssn", Cardinality: 1, Operations: createUpdate},
		{Name: "field_part_detail.attr0=volume", Label: "Volume Number", Aliases: []string{"field_part_detail.attr0=voume"}, Hub: "Publication.Volume", Cardinality: 1, Operations: createUpdate},
		{Name: "field_part_detail.attr0=issue", Label: "Issue Number", Hub: "Publication.Issue", Cardinality: 1, Operations: createUpdate},
		{Name: "field_part_detail.attr0=page", Label: "Page Numbers", Hub: "Publication.Pages", Cardinality: 1, Operations: createUpdate},
		{Name: "field_identifier.attr0=doi", Label: "DOI", Hub: "Identifiers.doi", Codec: "multi", Operations: createUpdate},
		{Name: "field_identifier.attr0=uri", Label: "Catalog or ArchivesSpace URL", Hub: "Identifiers.url", Codec: "multi", Operations: createUpdate},
		{Name: "field_identifier.attr0=call-number", Label: "Call Number", Hub: "Identifiers.call_number", Codec: "multi", Operations: createUpdate},
		{Name: "field_identifier.attr0=report-number", Label: "Report Number (included only on ATLSS and Fritz Lab spreadsheet)", Hub: "Identifiers.report_number", Codec: "multi", Operations: createUpdate},
		{Name: "field_rights", Label: "Rights Statement", Hub: "Rights", Codec: "multi", Operations: createUpdate},
		{Name: "field_access", Label: "Access", Hub: "AccessCondition", Cardinality: 1, Operations: createUpdate},
		{Name: "supplemental_file", Label: "Supplemental File", Hub: "Files.supplemental", Codec: "file", Operations: createUpdate},
		{Name: "unpublished_supplemental_file", Label: "Unpublished Supplemental Files", Hub: "Files.unpublished_supplemental", Codec: "file", Operations: []Operation{OperationUnpublishedSupplemental}},
	}

	targetFields := []Field{
		{Name: "id", Hub: "Extra.id", Operations: createOnly},
		{Name: "parent_id", Hub: "Extra.parent_id", Operations: createOnly},
		{Name: "field_weight", Hub: "Extra.field_weight", Operations: createUpdate},
		{Name: "node_id", Hub: "Extra.node_id", Operations: []Operation{OperationUpdate, OperationAddMedia}},
		{Name: "field_member_of", Hub: "Relations.member_of", Codec: "multi", Operations: createUpdate},
		{Name: "field_model", Hub: "ObjectModel", Operations: createUpdate},
		{Name: "file", Hub: "Files.primary", Operations: media},
		{Name: "field_add_coverpage", Hub: "AddCoverpage", Codec: "boolean", Operations: createUpdate},
		{Name: "title", Hub: "Title", Operations: createUpdate},
		{Name: "field_full_title", Hub: "FullTitle", Operations: createUpdate},
		{Name: "published", Hub: "IsPublic", Codec: "boolean", Operations: createUpdate},
		{Name: "field_linked_agent", Hub: "Contributors", Codec: "typed_relation", Operations: createUpdate},
		{Name: "field_department_name", Hub: "Departments", Codec: "multi", Operations: createUpdate},
		{Name: "field_resource_type", Hub: "ResourceType", OptionalForObjectModels: []string{"Page", "Sub-Collection"}, Operations: createUpdate},
		{Name: "field_genre", Hub: "Genre", Codec: "multi", Operations: createUpdate},
		{Name: "field_edtf_date_issued", Hub: "Dates.issued", Codec: "edtf", Operations: createUpdate},
		{Name: "field_date_season", Hub: "Extra.date_season", Operations: createUpdate},
		{Name: "field_edtf_date_captured", Hub: "Dates.captured", Codec: "edtf", Operations: createUpdate},
		{Name: "field_edtf_date_embargo", Hub: "Dates.available", Codec: "edtf", Operations: createUpdate},
		{Name: "field_publisher", Hub: "Publisher", Operations: createUpdate},
		{Name: "field_edition", Hub: "Edition", Operations: createUpdate},
		{Name: "field_language", Hub: "Language", Operations: createUpdate},
		{Name: "field_physical_form", Hub: "PhysicalForm", Codec: "multi", Operations: createUpdate},
		{Name: "field_media_type", Hub: "Files.mime_type", Operations: createUpdate},
		{Name: "field_extent", Hub: "Extent", Codec: "attributes", Operations: createUpdate},
		{Name: "field_digital_origin", Hub: "DigitalOrigin", Operations: createUpdate},
		{Name: "field_abstract", Hub: "Descriptions", Codec: "attributes", Operations: createUpdate},
		{Name: "field_note", Hub: "Notes", Codec: "attributes", Operations: createUpdate},
		{Name: "field_local_restriction", Hub: "LocalRestriction", Codec: "boolean", Operations: createUpdate},
		{Name: "field_subject_lcsh", Hub: "Subjects.lcsh", Codec: "multi", Operations: createUpdate},
		{Name: "field_keywords", Hub: "Subjects.keywords", Codec: "multi", Operations: createUpdate},
		{Name: "field_subjects_name", Hub: "Subjects.lcnaf", Codec: "multi", Operations: createUpdate},
		{Name: "field_geographic_subject", Hub: "Subjects.geographic", Codec: "typed", Operations: createUpdate},
		{Name: "field_subject_hierarchical_geo", Hub: "Subjects.getty_tgn", Codec: "multi", Operations: createUpdate},
		{Name: "field_related_item", Hub: "Publication.RelatedItem", Codec: "json", Operations: createUpdate},
		{Name: "field_part_detail", Hub: "Publication.Part", Codec: "attributes", Operations: createUpdate},
		{Name: "field_identifier", Hub: "Identifiers", Codec: "attributes", Operations: createUpdate},
		{Name: "field_rights", Hub: "Rights", Codec: "multi", Operations: createUpdate},
		{Name: "field_access", Hub: "AccessCondition", Operations: createUpdate},
		{Name: "supplemental_file", Hub: "Files.supplemental", Codec: "multi", Operations: createUpdate},
	}

	transformation := &Transformation{
		Version:     CurrentVersion,
		Name:        "fabricator-workbench",
		Description: "Google Sheets metadata to Islandora Workbench CSV",
		Source: Table{
			Format:              "csv",
			HeaderRows:          2,
			MachineHeaderRow:    0,
			HumanHeaderRow:      1,
			MultiValueSeparator: " ; ",
			Fields:              fields,
		},
		Target: Table{
			Format:              "islandora-workbench",
			HeaderRows:          1,
			MultiValueSeparator: "|",
			Fields:              targetFields,
		},
		Defaults: map[string]string{
			FileStagingRootDefault:                    "/mnt/islandora_staging",
			FileAllowedAbsoluteRootsDefault:           "/home|/mnt",
			SupplementalMediaUseTIDDefault:            "151326",
			SupplementalPublishedDefault:              "1",
			UnpublishedSupplementalMediaUseTIDDefault: "151326",
			UnpublishedSupplementalPublishedDefault:   "0",
		},
	}
	_ = transformation.SealFingerprint()
	return transformation
}
