// gen-categories fetches the arXiv category taxonomy page and generates
// a Go source file mapping category codes to human-readable labels.
//
// Usage:
//
//	go run ./format/arxiv/cmd/gen-categories
//	go run ./format/arxiv/cmd/gen-categories -file category_taxonomy.html
package main

import (
	"fmt"
	"io"
	"net/http"
	"os"
	"regexp"
	"sort"
	"strings"
	"time"
)

const (
	taxonomyURL = "https://arxiv.org/category_taxonomy"
	outputFile  = "format/arxiv/categories.go"
)

var categoryRe = regexp.MustCompile(`<h4>([a-zA-Z\-]+(?:\.[a-zA-Z\-]+)?) <span>\(([^)]+)\)</span></h4>`)

func main() {
	var data []byte
	var err error

	// Allow a local file for offline/testing use
	if len(os.Args) > 2 && os.Args[1] == "-file" {
		data, err = os.ReadFile(os.Args[2])
		if err != nil {
			fmt.Fprintf(os.Stderr, "reading file: %v\n", err)
			os.Exit(1)
		}
	} else {
		data, err = fetchTaxonomy()
		if err != nil {
			fmt.Fprintf(os.Stderr, "fetching taxonomy: %v\n", err)
			os.Exit(1)
		}
	}

	cats := extractCategories(string(data))
	if len(cats) == 0 {
		fmt.Fprintln(os.Stderr, "no categories found — check the HTML format")
		os.Exit(1)
	}

	if err := writeGoFile(cats); err != nil {
		fmt.Fprintf(os.Stderr, "writing output: %v\n", err)
		os.Exit(1)
	}

	fmt.Fprintf(os.Stderr, "wrote %d categories to %s\n", len(cats), outputFile)
}

func fetchTaxonomy() ([]byte, error) {
	client := &http.Client{Timeout: 30 * time.Second}
	resp, err := client.Get(taxonomyURL)
	if err != nil {
		return nil, fmt.Errorf("HTTP GET: %w", err)
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("unexpected status: %s", resp.Status)
	}
	return io.ReadAll(resp.Body)
}

func extractCategories(html string) map[string]string {
	matches := categoryRe.FindAllStringSubmatch(html, -1)
	cats := make(map[string]string, len(matches))
	for _, m := range matches {
		cats[m[1]] = m[2]
	}
	return cats
}

func writeGoFile(cats map[string]string) error {
	keys := make([]string, 0, len(cats))
	for k := range cats {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	var b strings.Builder
	b.WriteString("// Code generated by gen-categories; DO NOT EDIT.\n")
	b.WriteString("//go:generate go run ./cmd/gen-categories\n\n")
	b.WriteString("package arxiv\n\n")
	b.WriteString("// categoryLabels maps arXiv category codes to human-readable labels.\n")
	b.WriteString("var categoryLabels = map[string]string{\n")
	for _, k := range keys {
		fmt.Fprintf(&b, "\t%q: %q,\n", k, cats[k])
	}
	b.WriteString("}\n\n")
	b.WriteString("// CategoryLabel returns the human-readable label for an arXiv category code.\n")
	b.WriteString("// Returns an empty string if the code is unknown.\n")
	b.WriteString("func CategoryLabel(code string) string {\n")
	b.WriteString("\treturn categoryLabels[code]\n")
	b.WriteString("}\n")

	return os.WriteFile(outputFile, []byte(b.String()), 0o644)
}
